# Generated by Django 4.2.5 on 2023-09-17 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imageapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertier",
            name="tier",
        ),
        migrations.RemoveField(
            model_name="usertier",
            name="user",
        ),
        migrations.AddField(
            model_name="usertier",
            name="expiring_link_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usertier",
            name="name",
            field=models.CharField(default="Basic", max_length=255),
        ),
        migrations.AddField(
            model_name="usertier",
            name="original_link_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usertier",
            name="thumbnail_sizes",
            field=models.JSONField(default={"200px": 200}),
        ),
        migrations.AddField(
            model_name="usertier",
            name="users",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_tier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
