# Generated by Django 4.2.5 on 2023-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imageapp", "0002_remove_usertier_tier_remove_usertier_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertier",
            name="thumbnail_sizes",
            field=models.JSONField(default=dict),
        ),
    ]
