# Generated by Django 4.2.5 on 2023-09-17 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imageapp", "0003_alter_usertier_thumbnail_sizes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertier",
            name="users",
        ),
        migrations.AddField(
            model_name="usertier",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="user_tier", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
