# Generated by Django 4.2.5 on 2023-09-17 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imageapp", "0004_remove_usertier_users_usertier_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertier",
            name="users",
        ),
        migrations.AddField(
            model_name="usertier",
            name="users",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_tier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
