# Generated by Django 4.2.5 on 2023-09-17 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imageapp", "0005_remove_usertier_users_usertier_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Basic", max_length=255)),
                ("thumbnail_sizes", models.JSONField(default=dict)),
                ("original_link_enabled", models.BooleanField(default=False)),
                ("expiring_link_enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="usertier",
            name="expiring_link_enabled",
        ),
        migrations.RemoveField(
            model_name="usertier",
            name="name",
        ),
        migrations.RemoveField(
            model_name="usertier",
            name="original_link_enabled",
        ),
        migrations.RemoveField(
            model_name="usertier",
            name="thumbnail_sizes",
        ),
        migrations.RemoveField(
            model_name="usertier",
            name="users",
        ),
        migrations.AddField(
            model_name="usertier",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usertier",
            name="tier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="imageapp.tier",
            ),
        ),
    ]
