# Generated by Django 4.2.5 on 2023-09-18 14:29

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("imageapp", "0006_tier_remove_usertier_expiring_link_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(upload_to="images/"),
        ),
    ]
